# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastro1(object):
    def setupUi(self, cadastro1):
        cadastro1.setObjectName("cadastro1")
        cadastro1.resize(285, 288)
        cadastro1.setMinimumSize(QtCore.QSize(285, 288))
        cadastro1.setMaximumSize(QtCore.QSize(285, 288))
        icon = QtGui.QIcon.fromTheme("sleep.ico")
        cadastro1.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(cadastro1)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_goCadastro2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_goCadastro2.setGeometry(QtCore.QRect(100, 210, 81, 31))
        self.btn_goCadastro2.setObjectName("btn_goCadastro2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 40, 135, 149))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_nome = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nome.setFont(font)
        self.lbl_nome.setObjectName("lbl_nome")
        self.verticalLayout.addWidget(self.lbl_nome)
        self.txt_nome = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_nome.setObjectName("txt_nome")
        self.verticalLayout.addWidget(self.txt_nome)
        self.lbl_nome_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nome_2.setFont(font)
        self.lbl_nome_2.setObjectName("lbl_nome_2")
        self.verticalLayout.addWidget(self.lbl_nome_2)
        self.txt_cpf = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_cpf.setInputMask("")
        self.txt_cpf.setObjectName("txt_cpf")
        self.verticalLayout.addWidget(self.txt_cpf)
        self.lbl_nome_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nome_3.setFont(font)
        self.lbl_nome_3.setObjectName("lbl_nome_3")
        self.verticalLayout.addWidget(self.lbl_nome_3)
        self.txt_senha = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_senha.setObjectName("txt_senha")
        self.verticalLayout.addWidget(self.txt_senha)
        cadastro1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(cadastro1)
        self.statusbar.setObjectName("statusbar")
        cadastro1.setStatusBar(self.statusbar)

        self.retranslateUi(cadastro1)
        QtCore.QMetaObject.connectSlotsByName(cadastro1)

    def retranslateUi(self, cadastro1):
        _translate = QtCore.QCoreApplication.translate
        cadastro1.setWindowTitle(_translate("cadastro1", "ZSQ - Cadastro"))
        self.btn_goCadastro2.setText(_translate("cadastro1", "Avançar"))
        self.lbl_nome.setText(_translate("cadastro1", "Nome"))
        self.lbl_nome_2.setText(_translate("cadastro1", "CPF"))
        self.lbl_nome_3.setText(_translate("cadastro1", "Senha"))
