# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editar(object):
    def setupUi(self, editar):
        editar.setObjectName("editar")
        editar.resize(800, 530)
        editar.setMinimumSize(QtCore.QSize(800, 530))
        editar.setMaximumSize(QtCore.QSize(800, 530))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icone (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        editar.setWindowIcon(icon)
        editar.setStyleSheet("#editar\n"
"{\n"
"    \n"
"    \n"
"    background-image:url(C:/Users/Yuri/source/repos/ZSQ/ZSQ/imagens/ceu.png)\n"
"    \n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"#frame{\n"
"\n"
"    border-radius:10px;\n"
"    \n"
"    background-color:#0055aa;\n"
"    \n"
"    \n"
"\n"
"    \n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"#btn_goCadastro2\n"
"{\n"
"\n"
"    border-radius:15px;\n"
"    \n"
"    background-color: rgb(94, 197, 230);\n"
"    \n"
"    border-style:solid;\n"
"\n"
"    font-weight:bold;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"#lbl_estilo{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"#spinExerrciciosSemana{\n"
"\n"
"border-radius:10px;\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(editar)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_goCadastro2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_goCadastro2.setGeometry(QtCore.QRect(360, 430, 81, 41))
        self.btn_goCadastro2.setStyleSheet("")
        self.btn_goCadastro2.setObjectName("btn_goCadastro2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 50, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.lbl_idade = QtWidgets.QLabel(self.centralwidget)
        self.lbl_idade.setGeometry(QtCore.QRect(140, 100, 133, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_idade.setFont(font)
        self.lbl_idade.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_idade.setObjectName("lbl_idade")
        self.txt_idade = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_idade.setGeometry(QtCore.QRect(140, 140, 133, 20))
        self.txt_idade.setStyleSheet("background-color: rgb(34, 150, 213);\n"
"border-style:solid;\n"
"border-radius:15px;\n"
"color:white;")
        self.txt_idade.setObjectName("txt_idade")
        self.lbl_nome_3 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nome_3.setGeometry(QtCore.QRect(140, 180, 133, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nome_3.setFont(font)
        self.lbl_nome_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_nome_3.setObjectName("lbl_nome_3")
        self.lbl_nome_4 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nome_4.setGeometry(QtCore.QRect(140, 280, 281, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nome_4.setFont(font)
        self.lbl_nome_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_nome_4.setObjectName("lbl_nome_4")
        self.spinHorasDormidas = QtWidgets.QSpinBox(self.centralwidget)
        self.spinHorasDormidas.setGeometry(QtCore.QRect(540, 280, 141, 22))
        self.spinHorasDormidas.setStyleSheet("background-color: rgb(34, 150, 213);\n"
"color:white;")
        self.spinHorasDormidas.setObjectName("spinHorasDormidas")
        self.lbl_nome_5 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nome_5.setGeometry(QtCore.QRect(140, 310, 371, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nome_5.setFont(font)
        self.lbl_nome_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_nome_5.setObjectName("lbl_nome_5")
        self.spinXicarasCafe = QtWidgets.QSpinBox(self.centralwidget)
        self.spinXicarasCafe.setGeometry(QtCore.QRect(540, 310, 141, 22))
        self.spinXicarasCafe.setStyleSheet("background-color: rgb(34, 150, 213);\n"
"color:white;\n"
"")
        self.spinXicarasCafe.setObjectName("spinXicarasCafe")
        self.lbl_nome_6 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nome_6.setGeometry(QtCore.QRect(140, 340, 371, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nome_6.setFont(font)
        self.lbl_nome_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_nome_6.setObjectName("lbl_nome_6")
        self.spinExercicioSemana = QtWidgets.QSpinBox(self.centralwidget)
        self.spinExercicioSemana.setGeometry(QtCore.QRect(540, 340, 141, 22))
        self.spinExercicioSemana.setStyleSheet("background-color: rgb(34, 150, 213);\n"
"color:white;")
        self.spinExercicioSemana.setObjectName("spinExercicioSemana")
        self.lbl_nome_7 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nome_7.setGeometry(QtCore.QRect(140, 370, 371, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nome_7.setFont(font)
        self.lbl_nome_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_nome_7.setObjectName("lbl_nome_7")
        self.spinExercicioSemana_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinExercicioSemana_2.setGeometry(QtCore.QRect(540, 370, 141, 22))
        self.spinExercicioSemana_2.setStyleSheet("background-color: rgb(34, 150, 213);\n"
"color:white;")
        self.spinExercicioSemana_2.setObjectName("spinExercicioSemana_2")
        self.lbl_nome_9 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nome_9.setGeometry(QtCore.QRect(310, 180, 161, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nome_9.setFont(font)
        self.lbl_nome_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_nome_9.setObjectName("lbl_nome_9")
        self.lbl_nome_10 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nome_10.setGeometry(QtCore.QRect(490, 180, 191, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nome_10.setFont(font)
        self.lbl_nome_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_nome_10.setObjectName("lbl_nome_10")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 30, 641, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(60, 180, 98, 54))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Sexo_masculino = QtWidgets.QRadioButton(self.widget)
        self.Sexo_masculino.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Sexo_masculino.setFont(font)
        self.Sexo_masculino.setStyleSheet("color: rgb(255, 255, 255);")
        self.Sexo_masculino.setAutoRepeat(False)
        self.Sexo_masculino.setAutoExclusive(True)
        self.Sexo_masculino.setObjectName("Sexo_masculino")
        self.verticalLayout_4.addWidget(self.Sexo_masculino)
        self.Sexo_Feminino = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Sexo_Feminino.setFont(font)
        self.Sexo_Feminino.setStyleSheet("color: rgb(255, 255, 255);")
        self.Sexo_Feminino.setChecked(False)
        self.Sexo_Feminino.setAutoRepeat(False)
        self.Sexo_Feminino.setAutoExclusive(True)
        self.Sexo_Feminino.setObjectName("Sexo_Feminino")
        self.verticalLayout_4.addWidget(self.Sexo_Feminino)
        self.widget1 = QtWidgets.QWidget(self.frame)
        self.widget1.setGeometry(QtCore.QRect(230, 180, 61, 54))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Sono_AgitadoSim = QtWidgets.QRadioButton(self.widget1)
        self.Sono_AgitadoSim.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Sono_AgitadoSim.setFont(font)
        self.Sono_AgitadoSim.setStyleSheet("color: rgb(255, 255, 255);")
        self.Sono_AgitadoSim.setAutoRepeat(False)
        self.Sono_AgitadoSim.setAutoExclusive(True)
        self.Sono_AgitadoSim.setObjectName("Sono_AgitadoSim")
        self.verticalLayout.addWidget(self.Sono_AgitadoSim)
        self.Sono_AgitadoNao = QtWidgets.QRadioButton(self.widget1)
        self.Sono_AgitadoNao.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Sono_AgitadoNao.setFont(font)
        self.Sono_AgitadoNao.setStyleSheet("color: rgb(255, 255, 255);")
        self.Sono_AgitadoNao.setAutoRepeat(False)
        self.Sono_AgitadoNao.setAutoExclusive(True)
        self.Sono_AgitadoNao.setObjectName("Sono_AgitadoNao")
        self.verticalLayout.addWidget(self.Sono_AgitadoNao)
        self.widget2 = QtWidgets.QWidget(self.frame)
        self.widget2.setGeometry(QtCore.QRect(410, 180, 61, 54))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Drogalicita_SIM = QtWidgets.QRadioButton(self.widget2)
        self.Drogalicita_SIM.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Drogalicita_SIM.setFont(font)
        self.Drogalicita_SIM.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.Drogalicita_SIM.setAutoRepeat(False)
        self.Drogalicita_SIM.setAutoExclusive(True)
        self.Drogalicita_SIM.setObjectName("Drogalicita_SIM")
        self.verticalLayout_2.addWidget(self.Drogalicita_SIM)
        self.Drogalicita_NAO = QtWidgets.QRadioButton(self.widget2)
        self.Drogalicita_NAO.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Drogalicita_NAO.setFont(font)
        self.Drogalicita_NAO.setStyleSheet("color: rgb(255, 255, 255);")
        self.Drogalicita_NAO.setAutoRepeat(False)
        self.Drogalicita_NAO.setAutoExclusive(True)
        self.Drogalicita_NAO.setObjectName("Drogalicita_NAO")
        self.verticalLayout_2.addWidget(self.Drogalicita_NAO)
        self.frame.raise_()
        self.btn_goCadastro2.raise_()
        self.label.raise_()
        self.lbl_idade.raise_()
        self.txt_idade.raise_()
        self.lbl_nome_3.raise_()
        self.Sexo_masculino.raise_()
        self.Sexo_Feminino.raise_()
        self.lbl_nome_4.raise_()
        self.spinHorasDormidas.raise_()
        self.lbl_nome_5.raise_()
        self.spinXicarasCafe.raise_()
        self.lbl_nome_6.raise_()
        self.spinExercicioSemana.raise_()
        self.lbl_nome_7.raise_()
        self.spinExercicioSemana_2.raise_()
        self.lbl_nome_9.raise_()
        self.Sono_AgitadoSim.raise_()
        self.Sono_AgitadoNao.raise_()
        self.lbl_nome_10.raise_()
        self.Drogalicita_SIM.raise_()
        self.Drogalicita_NAO.raise_()
        editar.setCentralWidget(self.centralwidget)

        self.retranslateUi(editar)
        QtCore.QMetaObject.connectSlotsByName(editar)

    def retranslateUi(self, editar):
        _translate = QtCore.QCoreApplication.translate
        editar.setWindowTitle(_translate("editar", "ZSQ - Editar Cadastro"))
        self.btn_goCadastro2.setText(_translate("editar", "Avançar"))
        self.label.setText(_translate("editar", "Dados Pessoais"))
        self.lbl_idade.setText(_translate("editar", "Idade"))
        self.lbl_nome_3.setText(_translate("editar", "Qual o seu sexo?"))
        self.lbl_nome_4.setText(_translate("editar", "Quantas horas você dorme por dia:"))
        self.lbl_nome_5.setText(_translate("editar", "Quantas xícaras de café você toma por dia?"))
        self.lbl_nome_6.setText(_translate("editar", "Quantidade de dias que se exercita por semana:"))
        self.lbl_nome_7.setText(_translate("editar", "De 0 a 10 quanto stress você passa:"))
        self.lbl_nome_9.setText(_translate("editar", "Seu sono é agitado?"))
        self.lbl_nome_10.setText(_translate("editar", "Você usa drogas lícitas?"))
        self.Sexo_masculino.setText(_translate("editar", "Masculino"))
        self.Sexo_Feminino.setText(_translate("editar", "Feminino"))
        self.Sono_AgitadoSim.setText(_translate("editar", "Sim"))
        self.Sono_AgitadoNao.setText(_translate("editar", "Não"))
        self.Drogalicita_SIM.setText(_translate("editar", "Sim"))
        self.Drogalicita_NAO.setText(_translate("editar", "Não"))
