# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_Admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_adm(object):
    def setupUi(self, Tela_adm):
        Tela_adm.setObjectName("Tela_adm")
        Tela_adm.resize(928, 690)
        Tela_adm.setMinimumSize(QtCore.QSize(928, 690))
        Tela_adm.setMaximumSize(QtCore.QSize(928, 690))
        Tela_adm.setStyleSheet("#Tela_adm{\n"
"background-image:url(C:/Users/Yuri/source/repos/ZSQ/ZSQ/imagens/ceu.png)\n"
"}\n"
"\n"
"#lbl_txt{\n"
"color:white\n"
"\n"
"\n"
"}\n"
"\n"
"#BtnEditar_usuario{\n"
"    border-radius:15px;\n"
"    \n"
"    background-color: rgb(94, 197, 230);\n"
"    \n"
"    border-style:solid;\n"
"\n"
"    font-weight:bold;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"#Btn_Delete{\n"
"    border-radius:15px;\n"
"    \n"
"    background-color: rgb(94, 197, 230);\n"
"    \n"
"    border-style:solid;\n"
"\n"
"    font-weight:bold;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"#Btn_buscar{\n"
"    border-radius:15px;\n"
"    \n"
"    background-color: rgb(94, 197, 230);\n"
"    \n"
"    border-style:solid;\n"
"\n"
"    font-weight:bold;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"#Btn_cadastrousu{\n"
"\n"
"    border-radius:15px;\n"
"    \n"
"    background-color: rgb(94, 197, 230);\n"
"    \n"
"    border-style:solid;\n"
"\n"
"    font-weight:bold;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"#Btn_sair{\n"
"    border-radius:15px;\n"
"    \n"
"    background-color: rgb(94, 197, 230);\n"
"    \n"
"    border-style:solid;\n"
"\n"
"    font-weight:bold;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Tela_adm)
        self.centralwidget.setObjectName("centralwidget")
        self.BtnEditar_usuario = QtWidgets.QPushButton(self.centralwidget)
        self.BtnEditar_usuario.setGeometry(QtCore.QRect(80, 630, 75, 23))
        self.BtnEditar_usuario.setObjectName("BtnEditar_usuario")
        self.Btn_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Delete.setGeometry(QtCore.QRect(170, 630, 75, 23))
        self.Btn_Delete.setObjectName("Btn_Delete")
        self.Btn_cadastrousu = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_cadastrousu.setGeometry(QtCore.QRect(270, 630, 75, 23))
        self.Btn_cadastrousu.setObjectName("Btn_cadastrousu")
        self.Btn_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_buscar.setGeometry(QtCore.QRect(480, 50, 75, 23))
        self.Btn_buscar.setObjectName("Btn_buscar")
        self.lbl_txt = QtWidgets.QLabel(self.centralwidget)
        self.lbl_txt.setGeometry(QtCore.QRect(60, 30, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_txt.setFont(font)
        self.lbl_txt.setObjectName("lbl_txt")
        self.txt_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cpf.setGeometry(QtCore.QRect(60, 50, 401, 20))
        self.txt_cpf.setStyleSheet("background-color: rgb(34, 150, 213);\n"
"color:white;")
        self.txt_cpf.setObjectName("txt_cpf")
        self.Btn_sair = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_sair.setGeometry(QtCore.QRect(780, 630, 75, 23))
        self.Btn_sair.setObjectName("Btn_sair")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 20, 881, 651))
        self.frame.setStyleSheet("background-color:#0055aa;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(35, 130, 811, 451))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tableWidget.setPalette(palette)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(13)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(12, item)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(620, 10, 251, 101))
        self.label.setStyleSheet("background-repeat:no-repeat;\n"
"background-size: auto;\n"
"background-image:url(C:/Users/Yuri/source/repos/ZSQ/ZSQ/imagens/logo_1.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame.raise_()
        self.BtnEditar_usuario.raise_()
        self.Btn_Delete.raise_()
        self.Btn_cadastrousu.raise_()
        self.Btn_buscar.raise_()
        self.lbl_txt.raise_()
        self.txt_cpf.raise_()
        self.Btn_sair.raise_()
        Tela_adm.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Tela_adm)
        self.statusbar.setObjectName("statusbar")
        Tela_adm.setStatusBar(self.statusbar)

        self.retranslateUi(Tela_adm)
        QtCore.QMetaObject.connectSlotsByName(Tela_adm)

    def retranslateUi(self, Tela_adm):
        _translate = QtCore.QCoreApplication.translate
        Tela_adm.setWindowTitle(_translate("Tela_adm", "ZSQ - ADMIN"))
        self.BtnEditar_usuario.setText(_translate("Tela_adm", "Editar"))
        self.Btn_Delete.setText(_translate("Tela_adm", "Deletar"))
        self.Btn_cadastrousu.setText(_translate("Tela_adm", "Cadastrar"))
        self.Btn_buscar.setText(_translate("Tela_adm", "Buscar"))
        self.lbl_txt.setText(_translate("Tela_adm", "Buscar por CPF:"))
        self.txt_cpf.setInputMask(_translate("Tela_adm", "000.000.000-00"))
        self.Btn_sair.setText(_translate("Tela_adm", "Deslogar"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Tela_adm", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Tela_adm", "Senha"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Tela_adm", "CPF"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Tela_adm", "Admin"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Tela_adm", "Idade"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Tela_adm", "Sexo"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Tela_adm", "HoradeSono"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Tela_adm", "Café"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Tela_adm", "AlcoolOuCigarro"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Tela_adm", "Exercícios"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Tela_adm", "SonoAgitado"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Tela_adm", "NvlStress"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Tela_adm", "Previsão"))
