# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_logado.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Logado(object):
    def setupUi(self, Tela_Logado):
        Tela_Logado.setObjectName("Tela_Logado")
        Tela_Logado.resize(750, 500)
        Tela_Logado.setMinimumSize(QtCore.QSize(750, 500))
        Tela_Logado.setMaximumSize(QtCore.QSize(750, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/Icone-_1_.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Tela_Logado.setWindowIcon(icon)
        Tela_Logado.setStyleSheet("\n"
"\n"
"#btn_naoSolution{\n"
"    \n"
"    border-radius:15px;\n"
"    border:none;\n"
"    background-color: rgb(94, 197, 230);\n"
"    \n"
"    border-style:solid;\n"
"\n"
"    font-weight:bold;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"#btn_simSolution{\n"
"    \n"
"    border-radius:15px;\n"
"    border:none;\n"
"    background-color: rgb(94, 197, 230);\n"
"    \n"
"    border-style:solid;\n"
"\n"
"    font-weight:bold;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"#Btn_editar{\n"
"    border-radius:15px;\n"
"    \n"
"    background-color: rgb(94, 197, 230);\n"
"    \n"
"    border-style:solid;\n"
"\n"
"    font-weight:bold;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"#frame{\n"
"\n"
"    border-radius:10px;\n"
"    \n"
"    background-color:rgb(0, 85, 170);\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"#Tela_Logado{\n"
"\n"
"background-image:url(C:/Users/Yuri/source/repos/ZSQ/ZSQ/imagens/ceu.png)\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"#Btn_deslogar{\n"
"    border-radius:15px;\n"
"    border:none;\n"
"    background-color: rgb(94, 197, 230);\n"
"    \n"
"    border-style:solid;\n"
"\n"
"    font-weight:bold;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Tela_Logado)
        self.centralwidget.setObjectName("centralwidget")
        self.TextArea_info = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TextArea_info.setEnabled(False)
        self.TextArea_info.setGeometry(QtCore.QRect(119, 112, 256, 231))
        self.TextArea_info.setStyleSheet("background-color: rgb(34, 150, 213);\n"
"border-style:solid;\n"
"border-radius:15px;\n"
"color:white;")
        self.TextArea_info.setObjectName("TextArea_info")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 360, 261, 17))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.cb_listaSolucao = QtWidgets.QComboBox(self.centralwidget)
        self.cb_listaSolucao.setGeometry(QtCore.QRect(460, 110, 161, 23))
        self.cb_listaSolucao.setStyleSheet("background-color: rgb(34, 150, 213);\n"
"border-style:solid;\n"
"border-radius:15px;\n"
"color:white;")
        self.cb_listaSolucao.setObjectName("cb_listaSolucao")
        self.Btn_editar = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_editar.setGeometry(QtCore.QRect(480, 390, 131, 23))
        self.Btn_editar.setStyleSheet("border-radius:30px;")
        self.Btn_editar.setObjectName("Btn_editar")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 50, 631, 401))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_solucaoESCOLHIDA = QtWidgets.QLabel(self.frame)
        self.lbl_solucaoESCOLHIDA.setGeometry(QtCore.QRect(360, 90, 241, 221))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_solucaoESCOLHIDA.setFont(font)
        self.lbl_solucaoESCOLHIDA.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_solucaoESCOLHIDA.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_solucaoESCOLHIDA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_solucaoESCOLHIDA.setLineWidth(0)
        self.lbl_solucaoESCOLHIDA.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_solucaoESCOLHIDA.setScaledContents(False)
        self.lbl_solucaoESCOLHIDA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_solucaoESCOLHIDA.setWordWrap(True)
        self.lbl_solucaoESCOLHIDA.setIndent(0)
        self.lbl_solucaoESCOLHIDA.setObjectName("lbl_solucaoESCOLHIDA")
        self.lbl_nomeUsuario = QtWidgets.QLabel(self.frame)
        self.lbl_nomeUsuario.setGeometry(QtCore.QRect(110, 30, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nomeUsuario.setFont(font)
        self.lbl_nomeUsuario.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_nomeUsuario.setObjectName("lbl_nomeUsuario")
        self.btn_simSolution = QtWidgets.QPushButton(self.centralwidget)
        self.btn_simSolution.setGeometry(QtCore.QRect(130, 400, 91, 20))
        self.btn_simSolution.setObjectName("btn_simSolution")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_naoSolution = QtWidgets.QPushButton(self.centralwidget)
        self.btn_naoSolution.setGeometry(QtCore.QRect(244, 400, 91, 20))
        self.btn_naoSolution.setObjectName("btn_naoSolution")
        self.Btn_deslogar = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_deslogar.setGeometry(QtCore.QRect(554, 460, 101, 23))
        self.Btn_deslogar.setObjectName("Btn_deslogar")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.frame.raise_()
        self.TextArea_info.raise_()
        self.label_2.raise_()
        self.cb_listaSolucao.raise_()
        self.Btn_editar.raise_()
        self.layoutWidget.raise_()
        self.btn_simSolution.raise_()
        self.btn_naoSolution.raise_()
        self.Btn_deslogar.raise_()
        Tela_Logado.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tela_Logado)
        QtCore.QMetaObject.connectSlotsByName(Tela_Logado)

    def retranslateUi(self, Tela_Logado):
        _translate = QtCore.QCoreApplication.translate
        Tela_Logado.setWindowTitle(_translate("Tela_Logado", "ZSQ - Área do Usuário"))
        self.label_2.setText(_translate("Tela_Logado", "A solução está funcionando?"))
        self.Btn_editar.setText(_translate("Tela_Logado", "Editar"))
        self.lbl_solucaoESCOLHIDA.setText(_translate("Tela_Logado", "                                                                          \\\n"
"                             \\\n"
"                                                                          \\\n"
"                                                                           \\                                      "))
        self.lbl_nomeUsuario.setText(_translate("Tela_Logado", "Nome do usuário"))
        self.btn_simSolution.setText(_translate("Tela_Logado", "Sim"))
        self.btn_naoSolution.setText(_translate("Tela_Logado", "Não"))
        self.Btn_deslogar.setText(_translate("Tela_Logado", "Deslogar"))
